name = "wa-web-clone"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "WA_DB"
database_name = "wa-db"
database_id = "ae1f1b44-d518-4a36-a2e9-f5e355e8f4c1"
migrations_dir = "db/migrations"